environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    PYTHON: "C:\\conda"
    MINICONDA_VERSION: "latest"
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\.continuous-integration\\appveyor\\windows_sdk.cmd"
    PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                  # of 32 bit and 64 bit builds are needed, move this
                  # to the matrix section.

  matrix:
    - PYTHON_VERSION: "2.7"
    - PYTHON_VERSION: "3.4"
    - PYTHON_VERSION: "3.5"

install:
  # Install miniconda using a powershell script.
  - "powershell .continuous-integration/appveyor/install-miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "conda config --set always_yes yes --set changeps1 no"
  - "conda info -a"
  - "conda update -q conda"
  - "conda config --add channels conda-forge"
  - "conda create -q -n test-environment python=%PYTHON_VERSION% appdirs beautifulsoup4 future geojson isodate lxml mock numpy pandas pytables pytest requests suds-jurko freezegun html5lib<=0.9999999"
  - "activate test-environment"
  - pip install httpretty<=0.8.10
  - "conda install pip"
  - "python setup.py install"

build: false

test_script:
  - "%CMD_IN_ENV% python setup.py test"
